# Generated by Django 4.0.6 on 2022-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_detail_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_list',
            name='detail_purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='购买日期'),
        ),
    ]
