# Generated by Django 4.0.6 on 2022-08-23 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_detail_list_detail_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow_history',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('history_name', models.TextField(verbose_name='设备类型')),
                ('history_brand', models.CharField(max_length=64, verbose_name='设备品牌')),
                ('history_phone_id', models.IntegerField(verbose_name='设备编号')),
                ('history_source', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备来源')),
                ('history_IMEI', models.TextField(blank=True, null=True, verbose_name='设备IMEI号')),
                ('history_username', models.CharField(max_length=32, verbose_name='姓名')),
                ('history_borrow_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出时间')),
                ('history_restore_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('history_usage', models.TextField(blank=True, null=True, verbose_name='借用用途')),
            ],
            options={
                'db_table': 'borrow_history',
            },
        ),
        migrations.CreateModel(
            name='borrow_info',
            fields=[
                ('people_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('borrow_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出时间')),
                ('restore_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('borrow_usage', models.TextField(blank=True, null=True, verbose_name='借用用途')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='设备id')),
            ],
            options={
                'db_table': 'borrow_info',
            },
        ),
    ]
