# Generated by Django 4.0.6 on 2022-08-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_phone_info_user_alter_borrow_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_info',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.borrow_info', to_field='phone', verbose_name='用户表'),
        ),
    ]
